import DonationObject from '#models/donation-object'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    const objects = [
      {
        name: 'Ballon de foot',
        description: 'Légèrement usé, taille 5',
        type: true,
        status: 1,
        categorie: 'Sport & Loisirs',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Ballon de basket',
        description: 'Coupe du monde 2015, excellent état',
        type: false,
        status: 1,
        categorie: 'Sport & Loisirs',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Livre - Le Seigneur des Anneaux',
        description: 'Trilogie complète, édition de poche',
        type: true,
        status: 1,
        categorie: 'Culture & Livres',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: "Veste d'hiver",
        description: 'Taille M, couleur bleu marine, très chaude',
        type: true,
        status: 1,
        categorie: 'Vêtements',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Console de jeu (ancienne génération)',
        description: 'Fonctionnelle, vendue sans manettes',
        type: false,
        status: 2,
        categorie: 'Informatique & Tech',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Assiettes en porcelaine',
        description: 'Lot de 6 assiettes plates blanches',
        type: true,
        status: 1,
        categorie: 'Maison & Cuisine',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Tapis de yoga',
        description: 'Neuf, couleur verte, épaisseur 5mm',
        type: true,
        status: 1,
        categorie: 'Sport & Loisirs',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Ordinateur portable',
        description: 'Écran fissuré, pour pièces uniquement',
        type: false,
        status: 3,
        categorie: 'Informatique & Tech',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Jeu de construction pour enfants',
        description: 'Boîte presque complète (quelques pièces manquantes)',
        type: true,
        status: 1,
        categorie: 'Jouets & Enfants',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Chaussures de randonnée',
        description: 'Taille 42, très bon état',
        type: true,
        status: 1,
        categorie: 'Vêtements',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Micro-ondes',
        description: 'Fonctionne parfaitement, couleur noire',
        type: false,
        status: 1,
        categorie: 'Électroménager',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Guitare acoustique',
        description: 'Corde de Mi grave cassée',
        type: true,
        status: 2,
        categorie: 'Musique & Art',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Lot de stylos et crayons',
        description: 'Matériel de bureau neuf',
        type: true,
        status: 1,
        categorie: 'Bureau & Fournitures',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'Écran PC 24 pouces',
        description: 'Moniteur Full HD, quelques légères rayures',
        type: false,
        status: 1,
        categorie: 'Informatique & Tech',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
      {
        name: 'AMD EPYC 9965',
        description: 'AMD EPYC 9965 est un processeur serveur haut de gamme...',
        type: true,
        status: 1,
        categorie: 'Informatique & Tech',
        user_id: 1,
        imagePath: 'iqh2z90hp85nyx1196d4q0gn.png',
      },
    ]

    await DonationObject.createMany(objects)
  }
}
